NAME = ssed_loser

SRCS = main.cpp file_traitment.cpp
FLAGS = -Wall -Wextra  -Werror

OBJ = ${SRCS:.cpp=.o}

all : $(NAME)

$(NAME) : $(SRCS) $(OBJ) ssed.hpp
	c++ $(FLAGS) $(SRCS) -o $(NAME)


fclean :
	rm -rf $(OBJ) $(NAME)

clean :
	rm -rf $(OBJ)

re : fclean all
